#!/bin/bash

while true
do

# Logo

echo "============================================================"
curl -s https://raw.githubusercontent.com/StakeTake/script/main/log.sh | bash
echo "============================================================"

# Menu

PS3='Select an action: '
options=(
"Option 1"
"Option 2"
"Option 3"
"Exit"
)
select opt in "${options[@]}"
do
case $opt in

""Option 1")
echo "============================================================"
echo ""
echo "============================================================"

break
;;

"Exit")
exit
;;
*) echo "invalid option $REPLY";;
esac
done
done
